version: '3.8'

services:
  minio-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: minio-api
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Admin1234
    ports:
      - "9000:80"
    volumes:
      - ./data:/data

  minio-console:
    build:
      context: .
      dockerfile: Dockerfile.console
    container_name: minio-console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Admin1234
    ports:
      - "9001:80"
    volumes:
      - ./data:/data
