services:
  - type: web
    name: minio-hospital
    runtime: image
    image:
      url: quay.io/minio/minio:latest
    dockerCommand: server /data --console-address ":9000"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: tu_clave_segura
