services:
  - type: web
    name: minio-hospital
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: tu_clave_segura
